### ISSUE TITLE
改了下你的代码结构

### ISSUE THREAD

**Issue by rickytan** [xiaohanyu/oh-my-love#1]
发现你全用定时器做的，事实上 JS 中设置一堆定时器很影响性能。用 Promise 重写了部分代码，https://github.com/rickytan/MyLove

**Comment by xiaohanyu** [comment]
Oh，今天重新整理自己的 github 时才发现这个 issue 。谢谢回复，但是这个 demo 性质的 repo 实在是没有时间继续改进了，喵。
